trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  - group: 'cicdapp-variable-groups'

steps:
  - task: PowerShell@2
    displayName: 'Publish to Nuget'
    inputs:
      filePath: 'build.ps1'
      arguments: '-Target PushToNuget'
      pwsh: true
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |       
        Get-ChildItem -Path ./artifacts
      errorActionPreference: 'continue'
      pwsh: true
